### ISSUE TITLE
Switching tabs and coming back to bounceAround causes the ball to leave play-area

### ISSUE THREAD

**Issue by Tombez** [Kadin-Wilson/bounceAround#1]
On the frame that you return to bounceAround, the ball moves a proportional distance to how long was spend with another tab focused. 
I believe this is because the browser does not call animation frame callbacks while the tab is unfocused.

**Comment by Kadin-Wilson** [comment]
Nice catch. I think I should be able to fix this with some event listeners to pause and restart the game loop on window focus events. I will work on it.

**Comment by Kadin-Wilson** [comment]
Handling visibility change events seems to have resolved this issue.

**Comment by Tombez** [comment]
Commit 94dbc638258f1092500b380bcd7d57f888df1172
If you put the issue number `#1` in a commit message, it'll become a link on the commit, and Github will add a link from the issue to the commit.

**Comment by Kadin-Wilson** [comment]
Sweet
